version: '3'
services:
  nacos:
    image: 'nacos/nacos-server:v2.1.2'
    container_name: 'nacos'
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
      - 7848:7848
      - 9849:9849
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - /bsn/nacos/logs/:/home/nacos/logs
      - /bsn/nacos/plugins/:/home/nacos/plugins
      - /bsn/nacos/data/:/home/nacos/data
      - /bsn/nacos/conf/application.properties:/home/nacos/conf/application.properties
