version: "3"
services:
  ddc-oai-service:
    image: java11-cn:11.0.16.1
    container_name: ddc-oai
    working_dir: /bsn/ddc-oai
    restart: always
    network_mode: host
    # ports:
    #   - 18080:18080
    volumes:
      - /bsn/ddc-oai/pkg/ddc-oai.jar:/bsn/ddc-oai/ROOT.jar
      - /bsn/ddc-oai/logs/:/bsn/ddclogs/
      - /bsn/ddc-oai/script/:/bsn/script
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime
    environment:
      # 指定时区
      - TZ=Asia/Shanghai
    command: sh /bsn/script/start.sh
    