version: '3'
services:
  redis:
    image: 'redis:6.0.5'
    container_name: 'redis'
    restart: always
    tty: true
    volumes:
      - /bsn/redis/data:/data
      - /bsn/nacos/conf/redis.conf:/etc/redis/redis.conf
      - /bsn/nacos/logs:/logs
    ports:
      - 6379:6379
    command:
      - /bin/bash
      - -c
      - |
        echo 1024 > /proc/sys/net/core/somaxconn
        redis-server --requirepass "XXXXXXX"  # 自己设置密码
    privileged: true