# 启动顺序
# 1.ddc-swap-api，ddc-swap-job
# 2.ddc-base、ddc-account
# 3.ddc-ops、ddc-auth、ddc-opsjob
# 4.ddc-portal
# 5.ddc-oai
version: "3"
services:
  ddc-swap-api-service:
    image: java11-cn:11.0.16.1
    container_name: ddc-swap-api
    working_dir: /bsn/ddc-swap-api
    restart: always
    network_mode: host
    # ports:
    #   - 9070:9070
    volumes:
      - $PWD/swap-api/pkg/ddc-swap-api.jar:/bsn/ddc-swap-api/ROOT.jar
      - $PWD/ddclogs/:/bsn/ddclogs/
      - $PWD/swap-api/script/:/bsn/script
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime
    environment:
      # 指定时区
      - TZ=Asia/Shanghai
    command: sh /bsn/script/start.sh

  ddc-swap-job-ddc-service:
    image: java11-cn:11.0.16.1
    container_name: ddc-swap-job
    working_dir: /bsn/ddc-swap-job
    restart: always
    network_mode: host
    # ports:
    #   - 38021:38021
    volumes:
      - $PWD/swap-api/pkg/ddc-swap-job.jar:/bsn/ddc-swap-job/ROOT.jar
      - $PWD/ddclogs/:/bsn/ddclogs/
      - $PWD/swap-api/script/:/bsn/script
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime
    environment:
      # 指定时区
      - TZ=Asia/Shanghai
    command: sh /bsn/script/start.sh
    
  ddc-base-service:
    image: java11-cn:11.0.16.1
    container_name: ddc-base
    working_dir: /bsn/ddc-base
    restart: always
    network_mode: host
    # ports:
    #   - 8071:8071
    volumes:
      - $PWD/ddc-base/pkg/ddc-base.jar:/bsn/ddc-base/ROOT.jar
      - $PWD/ddc-base/script/:/bsn/script
      - $PWD/ddclogs/:/bsn/ddclogs/
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    command: sh /bsn/script/start.sh

  ddc-account-service:
    image: java11-cn:11.0.16.1
    container_name: ddc-account
    working_dir: /bsn/ddc-account
    restart: always
    network_mode: hosts
    # ports:
    #   - 8072:8072
    volumes:
      - $PWD/ddc-account/pkg/ddc-account.jar:/bsn/ddc-account/ROOT.jar
      - $PWD/ddc-account/script/:/bsn/script
      - $PWD/ddclogs/:/bsn/ddclogs/
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    command: sh /bsn/script/start.sh

  ddc-ops-service:
    image: java11-cn:11.0.16.1
    container_name: ddc-ops
    working_dir: /bsn/ddc-ops
    restart: always
    network_mode: host
    # ports:
    #   - 8081:8081
    volumes:
      - $PWD/ddc-ops/pkg/ddc-ops.jar:/bsn/ddc-ops/ROOT.jar
      - $PWD/ddclogs/:/bsn/ddclogs/
      - $PWD/ddc-ops/script/:/bsn/script
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime
    environment:
      # 指定时区
      - TZ=Asia/Shanghai
    command: sh /bsn/script/start.sh

  ddc-auth-service:
    image: java11-cn:11.0.16.1
    container_name: ddc-auth
    working_dir: /bsn/ddc-auth
    restart: always
    network_mode: host
    # ports:
    #   - 8091:8091
    volumes:
      - $PWD/ddc-auth/pkg/ddc-auth.jar:/bsn/ddc-auth/ROOT.jar
      - $PWD/ddclogs/:/bsn/ddclogs/
      - $PWD/ddc-auth/script/:/bsn/script
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime
    environment:
      # 指定时区
      - TZ=Asia/Shanghai
    command: sh /bsn/script/start.sh

  ddc-opsjob-service:
    image: java11-cn:11.0.16.1
    container_name: ddc-opsjob
    working_dir: /bsn/ddc-opsjob
    restart: always
    network_mode: host
    # ports:
    #   - 8061:8061
    volumes:
      - $PWD/ddc-opsjob/pkg/ddc-opsjob.jar:/bsn/ddc-opsjob/ROOT.jar
      - $PWD/ddclogs/:/bsn/ddclogs/
      - $PWD/ddc-opsjob/script/:/bsn/script
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime
    environment:
      # 指定时区
      - TZ=Asia/Shanghai
    command: sh /bsn/script/start.sh

  ddc-portal-service:
    image: java11-cn:11.0.16.1
    container_name: ddc-portal
    working_dir: /bsn/ddc-portal
    restart: always
    network_mode: host
    # ports:
    #   - 8072:8072
    volumes:
      - $PWD/ddc-portal/pkg/ddc-portal.jar:/bsn/ddc-portal/ROOT.jar
      - $PWD/ddclogs/:/bsn/ddclogs/
      - $PWD/ddc-portal/script/:/bsn/script
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime
    environment:
      # 指定时区
      - TZ=Asia/Shanghai
    command: sh /bsn/script/start.sh

  # 建议独立部署
  # ddc-oai-service:
  #   image: java11-cn:11.0.16.1
  #   container_name: ddc-oai
  #   working_dir: /bsn/ddc-oai
  #   restart: always
  #   network_mode: host
  #   # ports:
  #   #   - 18080:18080
  #   volumes:
  #     - $PWD/ddc-oai/pkg/ddc-oai.jar:/bsn/ddc-oai/ROOT.jar
  #     - /bsn/ddclogs/:/bsn/ddclogs/
  #     - $PWD/ddc-oai/script/:/bsn/script
  #     - /etc/hosts:/etc/hosts
  #     - /etc/localtime:/etc/localtime
  #   environment:
  #     # 指定时区
  #     - TZ=Asia/Shanghai
  #   command: sh /bsn/script/start.sh
