version: "3"
services:
  ddc-portal-service:
    image: java11-cn:11.0.16.1
    container_name: ddc-portal
    working_dir: /bsn/ddc-portal
    restart: always
    network_mode: host
    # ports:
    #   - 8072:8072
    volumes:
      - /bsn/ddc-portal/pkg/ddc-portal.jar:/bsn/ddc-portal/ROOT.jar
      - /bsn/ddc-portal/logs/:/bsn/ddclogs/
      - /bsn/ddc-portal/script/:/bsn/script
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime
    environment:
      # 指定时区
      - TZ=Asia/Shanghai
    command: sh /bsn/script/start.sh
    