version: "3"
services:
  ddc-ops-service:
    image: java11-cn:11.0.16.1
    container_name: ddc-ops
    working_dir: /bsn/ddc-ops
    restart: always
    network_mode: host
    # ports:
    #   - 8081:8081
    volumes:
      - /bsn/ddc-ops/pkg/ddc-ops.jar:/bsn/ddc-ops/ROOT.jar
      - /bsn/ddc-ops/logs/:/bsn/ddclogs/
      - /bsn/ddc-ops/script/:/bsn/script
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime
    environment:
      # 指定时区
      - TZ=Asia/Shanghai
    command: sh /bsn/script/start.sh
    