version: "3"
services:
  ddc-chainsrv-wenchang:
    image: java8:1.8.0_351
    container_name: ddc-chainsrv-wenchang
    working_dir: /bsn/chainService
    restart: always
    network_mode: host
    # ports:
    #   - 32020:32020
    volumes:
      - /bsn/ddc-chainsrv-wenchang/pkg/ddc-chainsrv-wenchang.jar:/bsn/chainService/ROOT.jar
      - /bsn/ddc-chainsrv-wenchang/logs/:/bsn/chainService/logs/ddc-chainsrv-wenchang
      - /bsn/ddc-chainsrv-wenchang/script/:/bsn/script
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime
    environment:
      # 指定时区
      - TZ=Asia/Shanghai
    command: sh /bsn/script/start.sh
    