version: '3'
services:
  mysql:
    image: mysql:5.7.39
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: xxxxxx # 自己设置
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - $PWD/data:/var/lib/mysql
      - $PWD/conf/my.cnf:/etc/mysql/my.cnf
      - $PWD/script:/mysql-script
    command:
      --max_connections=100000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password