version: "3"
services:
  ddc-account-service:
    image: java11-cn:11.0.16.1
    container_name: ddc-account
    working_dir: /bsn/ddc-account
    restart: always
    network_mode: host
    # ports:
    #   - 8072:8072
    volumes:
      - /bsn/ddc-account/pkg/ddc-account.jar:/bsn/ddc-account/ROOT.jar
      - /bsn/ddc-account/logs/:/bsn/ddclogs/
      - /bsn/ddc-account/script/:/bsn/script
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime
    environment:
      # 指定时区
      - TZ=Asia/Shanghai
    command: sh /bsn/script/start.sh
    