version: "3"
services:
  ddc-base-service:
    image: java11-cn:11.0.16.1
    container_name: ddc-base
    working_dir: /bsn/ddc-base
    restart: always
    network_mode: host
    # ports:
    #   - 8071:8071
    volumes:
      - $PWD/pkg/ddc-base.jar:/bsn/ddc-base/ROOT.jar
      - /bsn/ddclogs/:/bsn/ddclogs/
      - $PWD/script/:/bsn/script
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime
    environment:
      # 指定时区
      - TZ=Asia/Shanghai
    command: sh /bsn/script/start.sh
    