version: '3'
services:
  ddc-nginx:
    container_name: ddc-nginx
    image: openresty/openresty:latest
    restart: always
    volumes:
      - /bsn/ddc-nginx/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - /bsn/ddc-nginx/conf/ip_white.conf:/usr/local/openresty/nginx/conf/ip_white.conf
      - /bsn/ddc-nginx/stream:/etc/nginx/conf.d
      - /bsn/ddc-nginx/logs:/var/log/
      - /bsn/ddc-nginx/ssl:/etc/nginx/ssl
      - /etc/hosts:/etc/hosts
      - /bsn/ddc-nginx/html/operation/dist:/usr/local/openresty/nginx/html/operation
      - /bsn/ddc-nginx/html/portal/dist:/usr/local/openresty/nginx/html/portal
    ports:
      - "80:80"
      - "443:443"
      # - "8443:8443"
    environment:
        TZ: Asia/Shanghai